# Generated by Django 2.1.8 on 2019-05-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='check_date',
            field=models.DateField(null=True),
        ),
    ]
