# Generated by Django 2.1.8 on 2019-05-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='context',
            new_name='check',
        ),
    ]
