# Generated by Django 2.1.8 on 2019-05-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190514_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='check',
        ),
    ]
