<<<<<<< HEAD
# Generated by Django 2.1.8 on 2019-05-16 05:39
=======
# Generated by Django 2.1.8 on 2019-05-16 04:33
>>>>>>> 8f5f5d99ff2310839f38b264452dbc0d8d6ba051

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('uprate', models.FloatField(default=1)),
                ('downrate', models.FloatField(default=1)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('usercnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('poster_url', models.ImageField(blank=True, upload_to='')),
                ('audiCnt', models.IntegerField()),
                ('audinten', models.IntegerField()),
                ('audiChange', models.FloatField()),
                ('auidAcc', models.IntegerField()),
                ('userRating', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120)),
                ('value', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMatchMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updown', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.Movie'),
        ),
        migrations.AddField(
            model_name='match',
            name='user_down',
            field=models.ManyToManyField(blank=True, related_name='down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user_up',
            field=models.ManyToManyField(blank=True, related_name='up', to=settings.AUTH_USER_MODEL),
        ),
    ]
