# Generated by Django 2.1.8 on 2019-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='downrate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='uprate',
            field=models.FloatField(default=1),
        ),
    ]
