# Generated by Django 2.1.8 on 2019-05-13 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='down',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up', to=settings.AUTH_USER_MODEL),
        ),
    ]
