# Generated by Django 2.1.8 on 2019-05-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0003_usermatchmoney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermatchmoney',
            old_name='point',
            new_name='points',
        ),
    ]
