# Generated by Django 2.1.8 on 2019-05-13 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('momo', '0003_auto_20190513_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='down',
        ),
        migrations.RemoveField(
            model_name='match',
            name='up',
        ),
        migrations.AddField(
            model_name='match',
            name='user_down',
            field=models.ManyToManyField(blank=True, null=True, related_name='down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user_up',
            field=models.ManyToManyField(blank=True, null=True, related_name='up', to=settings.AUTH_USER_MODEL),
        ),
    ]
