# Generated by Django 2.1.8 on 2019-05-14 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0004_auto_20190514_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatchmoney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
