# Generated by Django 2.1.8 on 2019-05-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0004_auto_20190515_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='usercnt',
            field=models.IntegerField(default=0),
        ),
    ]
