# Generated by Django 2.1.8 on 2019-05-13 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0004_auto_20190513_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user_down',
            field=models.ManyToManyField(blank=True, related_name='down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_up',
            field=models.ManyToManyField(blank=True, related_name='up', to=settings.AUTH_USER_MODEL),
        ),
    ]
