# Generated by Django 2.1.8 on 2019-05-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0005_auto_20190513_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='audiChange',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='audiCnt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='audinten',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='auidAcc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='userRating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
