# Generated by Django 2.1.8 on 2019-05-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0006_auto_20190513_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='auidAcc',
            new_name='audiAcc',
        ),
    ]
